default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV['APPNAME_DATABASE_D'] %>
  username: <%= ENV['APPNAME_DATABASE_D_USER'] %>
  password: <%= ENV['APPNAME_DATABASE_D_PASSWORD'] %>
  host: localhost
  encoding: unicode

test:
  <<: *default
  database: db/test.postgresql

production:
  <<: *default
  database: db/production.postgresql
